wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1669949479.127771
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 16
      - 17
      - 23
      - 37
      4: 3.9.12
      5: 0.13.4
      8:
      - 5
      10:
      - 3
batch:
  desc: null
  value: 32
cuda_num:
  desc: null
  value: 0
iters:
  desc: null
  value: 100
log:
  desc: null
  value: true
lr:
  desc: null
  value: 0.01
mode:
  desc: null
  value: fedbn
mu:
  desc: null
  value: 0.01
percent:
  desc: null
  value: 0.1
project_name:
  desc: null
  value: fedbn
resume:
  desc: null
  value: false
save_path:
  desc: null
  value: ../checkpoint/fedavg/federated_medical
test:
  desc: null
  value: false
wk_iters:
  desc: null
  value: 1
